### ISSUE TITLE
assignment-3 Fibonacci sequence

### ISSUE THREAD

**Issue by 58bit23** [vtcbca/basic-programming-48bit23#2]
What is Fibonacci sequence?

**Comment by 48bit23** [comment]
The Fibonacci sequence is a series of numbers where each number is the sum of the two preceding ones, usually starting with 0 and 1.

**Comment by 58bit23** [comment]
Ok Can you give me a example of Fibonacci sequence?

**Comment by 48bit23** [comment]
Here’s an example of how the Fibonacci sequence works, starting from 0 and 1:

Start with the first two numbers: 0, 1.
Add the first two numbers to get the third number:
0+1=1
0+1=1 So the sequence is now: 0, 1, 1.
Add the second and third numbers to get the fourth number:
1+1=2
1+1=2 Now the sequence is: 0, 1, 1, 2.
Add the third and fourth numbers to get the fifth number:
1+2=3
1+2=3 Now the sequence is: 0, 1, 1, 2, 3.
Add the fourth and fifth numbers to get the sixth number:
2+3=5
2+3=5 Now the sequence is: 0, 1, 1, 2, 3, 5.
Add the fifth and sixth numbers to get the seventh number:
3+5=8
3+5=8 Now the sequence is: 0, 1, 1, 2, 3, 5, 8.

**Comment by 58bit23** [comment]
can you make fibonacci sequence which starts with6 and 8?

**Comment by 48bit23** [comment]
Starting with 6 and 8:
The first two numbers are 6 and 8.
Add the first two numbers to get the third number:
6+8=14
6+8=14
So the sequence is now: 6, 8, 14.
Add the second and third numbers to get the fourth number:
8+14=22
8+14=22
Now the sequence is: 6, 8, 14, 22.
Add the third and fourth numbers to get the fifth number:
14+22=36
14+22=36
Now the sequence is: 6, 8, 14, 22, 36.
Add the fourth and fifth numbers to get the sixth number:
22+36=58
22+36=58
Now the sequence is: 6, 8, 14, 22, 36, 58.
Add the fifth and sixth numbers to get the seventh number:
36+58=94
36+58=94
Now the sequence is: 6, 8, 14, 22, 36, 58, 94.
So the Fibonacci sequence starting with 6 and 8 looks like this:
6,8,14,22,36,58,94,…

**Comment by 58bit23** [comment]
what is the use fibonacci sequence?

**Comment by 48bit23** [comment]
Fibonacci retracements are the most common form of technical analysis based on the Fibonacci sequence. During a trend, Fibonacci retracements can be used to determine how deep a pullback may be.

**Comment by 58bit23** [comment]
Thanks @48bit23 for giving the positive resonse.

**Comment by 48bit23** [comment]
It's my pleasure !
