### ISSUE TITLE
assignment 5 Palindrome Checker

### ISSUE THREAD

**Issue by 56bit23** [vtcbca/basic-programming-48bit23#3]
What is Palindrome number?

**Comment by 48bit23** [comment]
A palindromic number (also known as a numeral palindrome or a numeric palindrome) is a number (such as 16461) that remains the same when its digits are reversed. In other words, it has [reflectional symmetry] across a vertical axis.

**Comment by 56bit23** [comment]
What are the example of Palindrom?

**Comment by 48bit23** [comment]
Examples are 1234321, 34543, abcba,etc...

**Comment by 56bit23** [comment]
Prove them.

**Comment by 48bit23** [comment]
Actual number :1234321
Reverse Order :1234321
Actual number = Reverse Order
Hence ,Proved !!

**Comment by 56bit23** [comment]
Ok Now I understand the palindrom.

**Comment by 48bit23** [comment]
Yeah that's damn easy !!!

**Comment by 56bit23** [comment]
Hmm thank you @48bit23 for your response.

**Comment by 48bit23** [comment]
It's my pleasure
