### ISSUE TITLE
Assignment-7  : Traiangle Pattern 

### ISSUE THREAD

**Issue by 55bit23** [vtcbca/basic-programming-48bit23#4]
Can you print a pattern where numbers start from the last row and decrease upwards?

**Comment by 48bit23** [comment]
Yes, calculate numbers for each row and decrement them as the rows progress upwards.

**Comment by 55bit23** [comment]
How do you make the program customizable for any symbol, not just numbers?

**Comment by 48bit23** [comment]
ake a symbol as input and use it instead of numbers:


```
> symbol = input("Enter a symbol: ")
> print(symbol, end=" ")
```

**Comment by 55bit23** [comment]
What happens if the user enters 0 for the number of rows?

**Comment by 48bit23** [comment]
The program will generate no output as no rows will be printed.

**Comment by 55bit23** [comment]
What is the simplest way to print a right-aligned triangle pattern? @48bit23

**Comment by 55bit23** [comment]
Simple just  Add spaces before the numbers in each row.
